//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_TB_SUREST
    {
        public string Guid { get; set; }
        public string ckdh { get; set; }
        public Nullable<decimal> sl2ok { get; set; }
        public Nullable<decimal> sl2 { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<decimal> WeiTuoId { get; set; }
    }
}
