//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_TB_ChuKuShenQing
    {
        public string GUID { get; set; }
        public string tdhm { get; set; }
        public string fphm { get; set; }
        public string opt1 { get; set; }
        public Nullable<System.DateTime> date0 { get; set; }
        public string smbname { get; set; }
        public string shydm { get; set; }
        public string scopaddr { get; set; }
        public string scoptel { get; set; }
        public string bmbname { get; set; }
        public string bhydm { get; set; }
        public string bcopaddr { get; set; }
        public string bcoptel { get; set; }
        public string cdfphm { get; set; }
        public string dlname { get; set; }
        public string pm { get; set; }
        public string cd { get; set; }
        public string ck { get; set; }
        public Nullable<decimal> YuanQuID { get; set; }
        public Nullable<System.DateTime> date4 { get; set; }
        public Nullable<decimal> htsl2 { get; set; }
        public Nullable<decimal> kdsl2 { get; set; }
        public Nullable<decimal> sl2 { get; set; }
        public string jhfs { get; set; }
        public string thr { get; set; }
        public string thtel { get; set; }
        public string thzh { get; set; }
        public string ysfs { get; set; }
        public string wldw { get; set; }
        public string shdw { get; set; }
        public string bz { get; set; }
        public string sldw2 { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string State { get; set; }
    }
}
