//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_TB_KAIPIAO_XIANGXI
    {
        public string Guid { get; set; }
        public string GoodsBillId { get; set; }
        public string SERIAL { get; set; }
        public string CODECARGO { get; set; }
        public string CODEPACK { get; set; }
        public string SUMMARY { get; set; }
        public string QUANTITY { get; set; }
        public string RATE { get; set; }
        public string CODE_MEASURE { get; set; }
        public string PRICE { get; set; }
        public string ZKE { get; set; }
        public string SFKC { get; set; }
        public string TDH { get; set; }
        public string FZ { get; set; }
    }
}
