//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_TB_KAIPIAO
    {
        public string Guid { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string IVNO { get; set; }
        public string IVDISPLAY { get; set; }
        public string CODECOMPANY { get; set; }
        public string CODECLIENT { get; set; }
        public string TOTAL { get; set; }
        public string REMARK { get; set; }
        public string CODEINOUT { get; set; }
        public string CODETRADE { get; set; }
        public string VGNO { get; set; }
        public string VESSEL { get; set; }
        public string VOYAGE { get; set; }
        public string CREATETIME { get; set; }
        public string CREATOR { get; set; }
        public string CREATORNAME { get; set; }
        public string PAYER { get; set; }
        public string PAPERNO { get; set; }
        public string CODEBILLTYPE { get; set; }
        public string TYR { get; set; }
        public string SHR { get; set; }
        public string FZ { get; set; }
        public string DZ { get; set; }
        public string YFZ { get; set; }
        public string ZDZ { get; set; }
        public string CZ { get; set; }
        public string FJ { get; set; }
        public string VEHICLES { get; set; }
        public string DCLC { get; set; }
        public string TOTALAMOUNT { get; set; }
        public string PLPB { get; set; }
        public string ZBPB { get; set; }
        public string TOTALWEIGHT { get; set; }
        public string QRZL { get; set; }
        public string UPPERTOTAL { get; set; }
        public string DRAWER { get; set; }
        public string CHECKER { get; set; }
        public string CODE_IVTEMPLATE { get; set; }
        public string CODE_BLINE { get; set; }
        public string CODE_DEPARTMENT { get; set; }
        public string PERIOD { get; set; }
        public string DRAWTIME { get; set; }
        public string QYD { get; set; }
        public string MDD { get; set; }
        public string FUZHU { get; set; }
        public string DLGRQ { get; set; }
        public string ZHG { get; set; }
        public string XHG { get; set; }
        public string YZM { get; set; }
        public string INVOICETYPE { get; set; }
        public string DEPOSER { get; set; }
        public string DEPOSETIME { get; set; }
        public string IVNO_HC { get; set; }
        public string BZ { get; set; }
        public string FPDM { get; set; }
        public string YFPDM { get; set; }
        public string YFPHM { get; set; }
        public string FPDM_ZZ { get; set; }
        public string PAPERNO_ZZ { get; set; }
        public string MARK_DS { get; set; }
        public string CODE_PAYER { get; set; }
        public string CODE_NOTETYPE { get; set; }
        public string CODE_NOTETEMPLATE { get; set; }
        public string State { get; set; }
        public Nullable<int> YuanQuID { get; set; }
    }
}
