//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_TB_Sure
    {
        public string NWM { get; set; }
        public string HUODAI { get; set; }
        public Nullable<decimal> PIECEWEIGHT { get; set; }
        public string VGNO { get; set; }
        public string BLNO { get; set; }
        public string MARK_GOOGSBILLTYPE { get; set; }
        public string MARK { get; set; }
        public string HETONGHAO { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string CreatPeople { get; set; }
        public string State { get; set; }
        public string GoodsName { get; set; }
        public decimal YuanQuID { get; set; }
        public string ShipName { get; set; }
        public string GoodsType { get; set; }
        public string YuanQuName { get; set; }
        public Nullable<decimal> ShuLiang { get; set; }
        public string GUID { get; set; }
        public string CreatPeopleID { get; set; }
        public string Cdbh { get; set; }
    }
}
