//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_BAOGUAN
    {
        public string Guid { get; set; }
        public Nullable<decimal> GoodsBillId { get; set; }
        public string BaoGuanShenQingRen { get; set; }
        public string BaoGuanLeiBie { get; set; }
        public string LiuXiang { get; set; }
        public string ChuanGongSi { get; set; }
        public Nullable<System.DateTime> ShenPiKaiShiRiQi { get; set; }
        public Nullable<System.DateTime> ShenPiJieShuRiQi { get; set; }
        public Nullable<decimal> MianShiQi { get; set; }
        public Nullable<decimal> MaoZhong { get; set; }
        public Nullable<decimal> JingZhong { get; set; }
        public Nullable<decimal> DanJia { get; set; }
        public string PiCi { get; set; }
        public string ZhongXinZuoYeDanHao { get; set; }
        public string JianShu { get; set; }
        public Nullable<decimal> BaoZhengJin { get; set; }
        public string GuanShui { get; set; }
        public Nullable<decimal> ZengZhiShui { get; set; }
        public string HuoZhi { get; set; }
        public string BaoGuanMiaoShu { get; set; }
        public string CreatPeople { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string BaoGuanDanHao { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> FangXingRiQi { get; set; }
        public Nullable<System.DateTime> BaoGuanRiQi { get; set; }
        public string BeiZhu { get; set; }
        public string GanZhong { get; set; }
    }
}
