//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_CANGDAN
    {
        public string Guid { get; set; }
        public Nullable<decimal> GoodsBillId { get; set; }
        public string CangDanHao { get; set; }
        public string TaiTouRen { get; set; }
        public string MaiTou { get; set; }
        public string PingMing { get; set; }
        public string MaoZhong { get; set; }
        public string MaoZhongDanWei { get; set; }
        public string JingZhong { get; set; }
        public string JingZhongDanWei { get; set; }
        public string TiDanHao { get; set; }
        public string JianShu { get; set; }
        public string JianShuDanWei { get; set; }
        public Nullable<System.DateTime> CangChuRiQi { get; set; }
        public Nullable<System.DateTime> QianFaRiQi { get; set; }
        public string YingWenChuanMing { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string CreatPeople { get; set; }
        public string HuiShouRen { get; set; }
        public Nullable<System.DateTime> HuiShouRiQi { get; set; }
        public string BoolHuiShou { get; set; }
        public string CangDanBeiZhu { get; set; }
        public string BeiZhu { get; set; }
        public string State { get; set; }
    }
}
