//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_FangHuoNeiBuShenPi
    {
        public string Guid { get; set; }
        public string ChuanMing { get; set; }
        public string HuoMing { get; set; }
        public string TiDanHao { get; set; }
        public string TiDanShu { get; set; }
        public string CunHuoRen { get; set; }
        public string TiHuoRen { get; set; }
        public string FangXingPiCi { get; set; }
        public string FangXingShuLiang { get; set; }
        public string ShengYuShuLiang { get; set; }
        public string BeiZhu { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string CreatPeople { get; set; }
        public string State { get; set; }
        public Nullable<decimal> GoodsBillId { get; set; }
        public string State_CangDan { get; set; }
        public string State_BaoGuan { get; set; }
        public string State_JiFei { get; set; }
    }
}
