//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_WEITUO
    {
        public string Guid { get; set; }
        public Nullable<decimal> GoodsBillId { get; set; }
        public string WeiTuoBianHao { get; set; }
        public string ZhiLingXiangMu { get; set; }
        public string ShenQingRen { get; set; }
        public Nullable<System.DateTime> XiaDaShiJian { get; set; }
        public string ZhiLingShuLiang { get; set; }
        public string FengPiaoChuanMingHangCi { get; set; }
        public string ZuiYeDanHao { get; set; }
        public string BeiZhu { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string CreatPeople { get; set; }
        public string State { get; set; }
    }
}
