//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_YEWUWEITUO
    {
        public string Guid { get; set; }
        public string BaoShuiLeiXing { get; set; }
        public string HuoMing { get; set; }
        public string HuoZhu { get; set; }
        public string ZhongWenChuanMing { get; set; }
        public string YingWenChuanMing { get; set; }
        public string HangCi { get; set; }
        public string TiDanHao { get; set; }
        public string TiDanShu { get; set; }
        public string JinZhong { get; set; }
        public Nullable<System.DateTime> JieDanRiQi { get; set; }
        public Nullable<System.DateTime> JiHuaDaoGangRiQi { get; set; }
        public string YuanChanDi { get; set; }
        public string LiaoHao { get; set; }
        public string DanJia { get; set; }
        public string HuoZhi { get; set; }
        public string XiangShu { get; set; }
        public string XiangXing { get; set; }
        public string YeWuLeiXing { get; set; }
        public string GuiGe { get; set; }
        public string BoolDanZheng { get; set; }
        public string BeiZhu { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string AddMan { get; set; }
        public string YeWuJinDu { get; set; }
        public string HeTongBiaoHao { get; set; }
        public Nullable<decimal> CreatPeapleId { get; set; }
    }
}
