//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_ZYLB_TBLL
    {
        public string Guid { get; set; }
        public string ZuoYeLeiBieMingCheng { get; set; }
        public string GongSiMingCheng { get; set; }
        public string JinChuKu { get; set; }
        public string DanJia { get; set; }
        public string BeiZhu { get; set; }
        public string CreatPeople { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<decimal> YuanQuId { get; set; }
        public Nullable<decimal> ShuLiang { get; set; }
        public Nullable<decimal> JinE { get; set; }
        public Nullable<decimal> TallBllId { get; set; }
        public Nullable<decimal> ConSignId { get; set; }
    }
}
