//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_APPVERSION
    {
        public decimal ID { get; set; }
        public string AppVersion { get; set; }
        public string AppApkUrl { get; set; }
        public string AppNote { get; set; }
        public string AppTitle { get; set; }
        public string State { get; set; }
    }
}
