//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DIC_JILIANG
    {
        public decimal ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Sjm { get; set; }
        public string ReMark { get; set; }
        public string creater { get; set; }
        public Nullable<System.DateTime> creatTime { get; set; }
    }
}
