//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Dic_YuanQu
    {
        public decimal ID { get; set; }
        public string YuanQuName { get; set; }
        public string PicPach { get; set; }
        public string CODECOMPANY { get; set; }
        public string codeuser { get; set; }
        public string password { get; set; }
    }
}
