//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_CODE_SECTION
    {
        public decimal ID { get; set; }
        public decimal CODE_COMPANY { get; set; }
        public string CODE_COMPANY_Name { get; set; }
        public string CODE_SECTION { get; set; }
        public string SECTION { get; set; }
        public string LOGOGRAM { get; set; }
        public string REMARK { get; set; }
        public string MARK_FORBID { get; set; }
    }
}
