//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_CODE_STORAGE
    {
        public decimal ID { get; set; }
        public decimal SECTION_ID { get; set; }
        public string CODE_STORAGE { get; set; }
        public string STORAGEName { get; set; }
        public string LOGOGRAM { get; set; }
        public string REMARK { get; set; }
        public string THISTYPE { get; set; }
        public string OUT_TYPE { get; set; }
        public string FULLNAME { get; set; }
        public string ENGINE { get; set; }
        public string UNITCAPACITY { get; set; }
        public Nullable<decimal> TRANS_DISTANCE { get; set; }
        public string INOUTTYPE { get; set; }
        public string NUM_VBOOTH { get; set; }
        public string NUM_BOOTH { get; set; }
        public string AREA { get; set; }
        public string CUBAGE { get; set; }
        public string EFFECT_AREA { get; set; }
        public string AREA_USERATE { get; set; }
        public string UNIT_LOAD_TECH_FIXED { get; set; }
        public string UNIT_LOAD_USE_FIXED { get; set; }
        public string WAREHOUSE_CAPACITY { get; set; }
        public string AVG_WAREHOUSE_CAPACITY { get; set; }
        public string THROUGH_ABILITY { get; set; }
        public string VOLUME { get; set; }
        public string IPORT_CODE_COMPANY { get; set; }
        public string CODE_SCHEME { get; set; }
        public string CODE_SCHEMEITEM { get; set; }
        public string LAT { get; set; }
        public string LOT { get; set; }
        public string CODE_CLIENT { get; set; }
        public string ISTC { get; set; }
        public Nullable<decimal> MARK_FORBID { get; set; }
        public string STORAGETYPE { get; set; }
        public string CODE_WORKINGAREA { get; set; }
    }
}
