//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_HS_TALLYBILL
    {
        public decimal ID { get; set; }
        public string TBNO { get; set; }
        public decimal CONSIGN_ID { get; set; }
        public string CGNO { get; set; }
        public string CODE_SECTION { get; set; }
        public Nullable<System.DateTime> SIGNDATE { get; set; }
        public string CODE_OPSTYPE { get; set; }
        public Nullable<decimal> PIECEWEIGHT { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public string CODE_QUALITY { get; set; }
        public string CODE_WORKTEAM { get; set; }
        public Nullable<System.DateTime> BEGINTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string REMARK { get; set; }
        public string USERNAME { get; set; }
        public string CODE_TALLYMAN { get; set; }
        public string TALLYMAN { get; set; }
        public string MARK_CLEARBOOTH { get; set; }
        public Nullable<decimal> TRAINNUM { get; set; }
        public string CODE_LOADPLACE { get; set; }
        public string TALLYNUMRIGHT { get; set; }
        public Nullable<decimal> CONTAINERNUM { get; set; }
        public string State { get; set; }
        public string CAOZUO { get; set; }
        public string FANGSHI { get; set; }
        public string CHANGORCAR { get; set; }
        public string GOODSBILL { get; set; }
        public Nullable<decimal> XIANGSHU { get; set; }
        public string GONGBAN { get; set; }
        public string STORAG { get; set; }
        public string Type { get; set; }
        public string CleraNum { get; set; }
        public string GoodsName { get; set; }
        public Nullable<decimal> YuanQuID { get; set; }
        public string HangCi { get; set; }
        public string HuoDai { get; set; }
        public string ChuanMing { get; set; }
        public string BanCi { get; set; }
        public string Shr { get; set; }
        public Nullable<decimal> DuanMu { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<decimal> PiZhong { get; set; }
        public string ZuoYeLeiXIng { get; set; }
    }
}
