//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_CODE_BOOTH
    {
        public decimal ID { get; set; }
        public decimal Storage_ID { get; set; }
        public string TB_CODE_BOOTH { get; set; }
        public string CODE_BOOTH { get; set; }
        public string BOOTH { get; set; }
        public string LOGOGRAM { get; set; }
        public string REMARK { get; set; }
        public string MARK_FORBID { get; set; }
        public string color { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> pageX { get; set; }
        public Nullable<decimal> pageY { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
    }
}
