//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_CHENGBEN
    {
        public decimal ID { get; set; }
        public string FeiMuZhongLei { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> GoodsBill_id { get; set; }
        public Nullable<decimal> ShuLiang { get; set; }
        public Nullable<decimal> ChengBenFeiLv { get; set; }
        public Nullable<decimal> ChengBenJinE { get; set; }
        public string WaiFuDanWei { get; set; }
        public Nullable<System.DateTime> WaiFuRiQi { get; set; }
        public string State { get; set; }
        public string WaiFuFeiMu { get; set; }
    }
}
