//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_HC_CONSIGN
    {
        public decimal ID { get; set; }
        public decimal GOODSBILL_ID { get; set; }
        public string CGNO { get; set; }
        public string CODE_OPERATION { get; set; }
        public string WeiTuoRen { get; set; }
        public string ShouHuoRen { get; set; }
        public string CODE_TRANS { get; set; }
        public Nullable<System.DateTime> WeiTuoTime { get; set; }
        public string BLNO { get; set; }
        public Nullable<decimal> PLANAMOUNT { get; set; }
        public Nullable<decimal> PLANWEIGHT { get; set; }
        public Nullable<decimal> PLANVOLUME { get; set; }
        public string CONTAINERTYPE { get; set; }
        public Nullable<decimal> CONTAINERNUM { get; set; }
        public string PAPERYNO { get; set; }
        public string BoolQuanLuYun { get; set; }
        public string SPONSOR { get; set; }
        public string Phone { get; set; }
        public string CREATORNAME { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> AUDITTIME { get; set; }
        public string AUDITORNAME { get; set; }
        public string CaoZuoGuoCheng { get; set; }
        public string BeiZhu { get; set; }
        public string HengZhong { get; set; }
        public string State { get; set; }
        public string GoodsBill_Num { get; set; }
        public Nullable<decimal> YuanQuID { get; set; }
        public string CarTeam { get; set; }
        public string GoodsType { get; set; }
        public string CarMan { get; set; }
        public string CarManPhone { get; set; }
        public string BillBranch { get; set; }
        public string BillVolume { get; set; }
        public string jccj { get; set; }
        public string GoodsName { get; set; }
        public string ShipName { get; set; }
        public string TestingVolume { get; set; }
        public string VGNO { get; set; }
        public string jbr { get; set; }
        public Nullable<decimal> FactNum { get; set; }
        public Nullable<decimal> FactNumW { get; set; }
        public string RejectReason { get; set; }
        public string LaiYuan { get; set; }
        public string MaiFangName { get; set; }
        public string MaiFangName2 { get; set; }
        public string Ckdh { get; set; }
        public string WeiTuoBianHao { get; set; }
        public string ZhiLingXiangMu { get; set; }
        public string ShenQingRen { get; set; }
        public Nullable<System.DateTime> XiaDaShiJian { get; set; }
        public string ZhiLingShuLiang { get; set; }
        public string FengPiaoChuanMingHangCi { get; set; }
        public string ZuiYeDanHao { get; set; }
        public string BoolQC { get; set; }
    }
}
