//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_HS_STOCKDORMANT
    {
        public decimal ID { get; set; }
        public string CODE_STORAGE { get; set; }
        public string CODE_BOOTH { get; set; }
        public string GBNO { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public Nullable<System.DateTime> FIRST_INDATE { get; set; }
        public Nullable<System.DateTime> BOOTH_INDATE { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> LastEidTime { get; set; }
        public string TALLYBILL_ID { get; set; }
        public string HuoDai { get; set; }
        public string GoodsName { get; set; }
        public Nullable<decimal> YuanQuID { get; set; }
    }
}
