//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_HC_GOODSBILL
    {
        public decimal ID { get; set; }
        public string GBNO { get; set; }
        public string CODE_INOUT { get; set; }
        public string NWM { get; set; }
        public Nullable<decimal> C_GOODSAGENT_ID { get; set; }
        public string C_GOODSAGENT_NAME { get; set; }
        public Nullable<decimal> CODE_PACK_ID { get; set; }
        public string CODE_PACK_NAME { get; set; }
        public Nullable<decimal> PIECEWEIGHT { get; set; }
        public string VGNO { get; set; }
        public string MAITOU { get; set; }
        public string BLNO { get; set; }
        public Nullable<decimal> PLANAMOUNT { get; set; }
        public Nullable<decimal> PLANWEIGHT { get; set; }
        public string MARK_GOOGSBILLTYPE { get; set; }
        public string MARK { get; set; }
        public string CHANGCUNLIANG { get; set; }
        public string KEBANLIWEITUOLIANG { get; set; }
        public Nullable<decimal> JINXIANGZONGSHU { get; set; }
        public Nullable<decimal> ZAICHANGXIANGSHU { get; set; }
        public string HETONGHAO { get; set; }
        public string HETONGBIANMA { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string CreatPeople { get; set; }
        public string State { get; set; }
        public string C_GOODS { get; set; }
        public Nullable<decimal> YuanQuID { get; set; }
        public string CONTRACT_Guid { get; set; }
        public string ContoractNumber { get; set; }
        public string ShipName { get; set; }
        public string KunCun { get; set; }
        public string jcjs { get; set; }
        public string jccj { get; set; }
        public string GoodsType { get; set; }
        public string KunCunW { get; set; }
        public string HuoZhu { get; set; }
        public Nullable<decimal> SuoHuoKunCunW { get; set; }
        public Nullable<decimal> SuoHuoKunCun { get; set; }
        public Nullable<decimal> Fyjehj { get; set; }
        public Nullable<decimal> Lkjehj { get; set; }
        public Nullable<decimal> Sryk { get; set; }
        public Nullable<decimal> ChengBenJinE { get; set; }
        public Nullable<decimal> LiRunZongE { get; set; }
        public Nullable<decimal> HuiShouLv { get; set; }
        public Nullable<decimal> ShiJiJInKu { get; set; }
        public Nullable<decimal> ShiJiChuKu { get; set; }
        public Nullable<decimal> KaiPiaoJineHJ { get; set; }
        public Nullable<decimal> KaiPiaoShuiHouHJ { get; set; }
        public Nullable<decimal> WeiKaiPiaoJineHJ { get; set; }
        public Nullable<decimal> WeiKaiPiaoShuiHouHJ { get; set; }
        public Nullable<decimal> YinShouZhangKuanYue { get; set; }
        public string RejectReason { get; set; }
        public Nullable<decimal> HuoZhi { get; set; }
        public Nullable<decimal> SysUserID { get; set; }
        public Nullable<decimal> CreatorRoleId { get; set; }
        public Nullable<decimal> YikaiPiaoYinShouYuE { get; set; }
        public Nullable<decimal> WeiKaiPiaoLiRun { get; set; }
        public Nullable<decimal> WeiKaiPiaoYingShouYuE { get; set; }
        public string State_FaPiao { get; set; }
        public string State_JiFei { get; set; }
        public string State_JieSuan { get; set; }
        public string Cgno { get; set; }
        public string BaoShuiLeiXing { get; set; }
        public string YingWenChuanMing { get; set; }
        public Nullable<System.DateTime> JieDanRiQi { get; set; }
        public Nullable<System.DateTime> JiHuaDaoGangRiQi { get; set; }
        public string YuanChanDi { get; set; }
        public string LiaoHao { get; set; }
        public string DanJia { get; set; }
        public string XiangShu { get; set; }
        public string XiangXing { get; set; }
        public string YeWuLeiXing { get; set; }
        public string GuiGe { get; set; }
        public string BoolDanZheng { get; set; }
        public string State_FeiShou { get; set; }
        public string SuoShuCangKu { get; set; }
        public string GanZhong { get; set; }
    }
}
