//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_CODE_CAOZUO
    {
        public decimal ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string DISPLAYNAME { get; set; }
        public string CODE_OPBTYPE { get; set; }
        public string CODE_CARRIER_S { get; set; }
        public string CODE_CARRIER_E { get; set; }
    }
}
