//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_HC_CONTRACT_DETAILED
    {
        public string Guid { get; set; }
        public string CONTRACT_Guid { get; set; }
        public string HuoZhong { get; set; }
        public string HuoMing { get; set; }
        public string FeiMuZhongLei { get; set; }
        public string JiLiangDanWei { get; set; }
        public Nullable<decimal> DanJia { get; set; }
        public Nullable<decimal> MianDuiCunTianShu { get; set; }
        public string BiaoZhi { get; set; }
        public string BeiZhu { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<System.DateTime> LastEdiTime { get; set; }
        public string State { get; set; }
        public string ShuiE { get; set; }
        public string YunFei { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> ChengBenFeiLv { get; set; }
        public string ChengBenJiFeiYiJu { get; set; }
        public string FeiMuZhongLeiCode { get; set; }
        public string HuoMingCode { get; set; }
    }
}
