//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TB_JIESUAN
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> Time1 { get; set; }
        public Nullable<System.DateTime> Time2 { get; set; }
        public Nullable<decimal> KaiPiaoJinE { get; set; }
        public string KaiPianDanWei { get; set; }
        public Nullable<System.DateTime> KaiPiaoRiQi { get; set; }
        public Nullable<decimal> LaiKuanJinE { get; set; }
        public Nullable<System.DateTime> LaiKuanShiJian { get; set; }
        public string LaiKuanDanWei { get; set; }
        public string FeiMuZhongLei { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> GoodsBill_id { get; set; }
        public Nullable<decimal> YuShouJinE { get; set; }
        public string KaiPiao_State { get; set; }
    }
}
