//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_GOODSAGENT> C_GOODSAGENT { get; set; }
        public DbSet<Sys_Menu> Sys_Menu { get; set; }
        public DbSet<Sys_Role> Sys_Role { get; set; }
        public DbSet<Sys_User> Sys_User { get; set; }
        public DbSet<C_DIC_JILIANG> C_DIC_JILIANG { get; set; }
        public DbSet<C_GOODS> C_GOODS { get; set; }
        public DbSet<C_TB_CODE_INOUT> C_TB_CODE_INOUT { get; set; }
        public DbSet<C_TB_CODE_TRADE> C_TB_CODE_TRADE { get; set; }
        public DbSet<C_Dic_YuanQu> C_Dic_YuanQu { get; set; }
        public DbSet<C_TB_CODE_PACK> C_TB_CODE_PACK { get; set; }
        public DbSet<C_TB_CODE_SECTION> C_TB_CODE_SECTION { get; set; }
        public DbSet<C_TB_CODE_VOYAGE> C_TB_CODE_VOYAGE { get; set; }
        public DbSet<C_TB_CODE_STORAGE> C_TB_CODE_STORAGE { get; set; }
        public DbSet<C_TB_CODE_CAOZUO> C_TB_CODE_CAOZUO { get; set; }
        public DbSet<C_TB_CODE_CUSTOMER> C_TB_CODE_CUSTOMER { get; set; }
        public DbSet<C_TB_HS_STOCKDORMANT> C_TB_HS_STOCKDORMANT { get; set; }
        public DbSet<C_TB_HS_TALLYBILL> C_TB_HS_TALLYBILL { get; set; }
        public DbSet<C_TB_CODE_BOOTH> C_TB_CODE_BOOTH { get; set; }
        public DbSet<C_CARTEAM> C_CARTEAM { get; set; }
        public DbSet<C_TB_HC_CONTRACT_DETAILED> C_TB_HC_CONTRACT_DETAILED { get; set; }
        public DbSet<C_GOODSTYPE> C_GOODSTYPE { get; set; }
        public DbSet<C_TB_HC_CONTRACT_FILES> C_TB_HC_CONTRACT_FILES { get; set; }
        public DbSet<C_TB_SHOUFEI> C_TB_SHOUFEI { get; set; }
        public DbSet<SYS_LOGINLOG> SYS_LOGINLOG { get; set; }
        public DbSet<C_TB_HC_CONSIGN_FILES> C_TB_HC_CONSIGN_FILES { get; set; }
        public DbSet<SYS_OperateLogs> SYS_OperateLogs { get; set; }
        public DbSet<C_TB_CHENGBEN> C_TB_CHENGBEN { get; set; }
        public DbSet<C_TB_JIESUAN> C_TB_JIESUAN { get; set; }
        public DbSet<B_TB_ZhuanYiInfo> B_TB_ZhuanYiInfo { get; set; }
        public DbSet<C_APPVERSION> C_APPVERSION { get; set; }
        public DbSet<B_TB_ChuKuShenQing> B_TB_ChuKuShenQing { get; set; }
        public DbSet<C_DIC_GUIZE> C_DIC_GUIZE { get; set; }
        public DbSet<C_TB_ZHIXINGFEILV> C_TB_ZHIXINGFEILV { get; set; }
        public DbSet<C_Charge> C_Charge { get; set; }
        public DbSet<C_TB_HC_CONTRACT> C_TB_HC_CONTRACT { get; set; }
        public DbSet<B_TB_KAIPIAO> B_TB_KAIPIAO { get; set; }
        public DbSet<B_TB_KAIPIAO_XIANGXI> B_TB_KAIPIAO_XIANGXI { get; set; }
        public DbSet<B_TB_SUREST> B_TB_SUREST { get; set; }
        public DbSet<B_TB_KAIPIAOJILU> B_TB_KAIPIAOJILU { get; set; }
        public DbSet<BS_YEWUWEITUO> BS_YEWUWEITUO { get; set; }
        public DbSet<B_TB_Sure> B_TB_Sure { get; set; }
        public DbSet<C_TB_HC_GOODSBILL> C_TB_HC_GOODSBILL { get; set; }
        public DbSet<BS_FangHuoNeiBuShenPi> BS_FangHuoNeiBuShenPi { get; set; }
        public DbSet<BS_C_TAITOUREN> BS_C_TAITOUREN { get; set; }
        public DbSet<BS_C_PINGMING> BS_C_PINGMING { get; set; }
        public DbSet<BS_BAOGUAN> BS_BAOGUAN { get; set; }
        public DbSet<BS_BAOJIAN> BS_BAOJIAN { get; set; }
        public DbSet<BS_CANGDAN> BS_CANGDAN { get; set; }
        public DbSet<BS_FANGHUOZHILING> BS_FANGHUOZHILING { get; set; }
        public DbSet<BS_WEITUO> BS_WEITUO { get; set; }
        public DbSet<C_TB_HC_CONSIGN> C_TB_HC_CONSIGN { get; set; }
        public DbSet<BS_LAOWUZUOYELEIBIE> BS_LAOWUZUOYELEIBIE { get; set; }
        public DbSet<Sys_appMenu> Sys_appMenu { get; set; }
        public DbSet<BS_ZYLB_TBLL> BS_ZYLB_TBLL { get; set; }
    }
}
