//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public decimal ID { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public Nullable<decimal> roleId { get; set; }
        public string roleName { get; set; }
        public string state { get; set; }
        public string email { get; set; }
        public Nullable<decimal> YuanQuId { get; set; }
        public Nullable<decimal> HuoDaiId { get; set; }
    }
}
